### ISSUE TITLE
VelocyJack deserialization not always called

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-java-driver-async#13] opened 2018-07-17 19:07 UTC
I have configured VelocyJack deserialization as per the docs. I note that in some cases, this deserializer is not called. Specifically, I am testing some code that simply does:

```
// 1
collection.insertDocument(doc)
...
// 2
collection.getDocument(key, MyDoc::class.java, DocumentReadOptions())
```

and the built-in default deserializer is being called at (2), not the VelocyJack deserializer. This was driving me nuts until I attached a debugger to the system to determine that the wrong deserializer was being called at `ArangoExecutor.createResult`.

ArangoExecutor upon initialization always requests the INTERNAL serializer, even if a custom one is defined.

Clearly the custom serialization is a work in progress. I'm gonna switch back to the default serialization for now.

**Comment by fdominik** [comment] 2019-07-04 06:25
I run into the same issues. However I realized that query() is the only method, which works correctly. So in order to getDcoument, I am just calling query() method with `"RETURN DOCUMENT(@docId)"` as the String query.

Probably related to https://github.com/arangodb/arangodb-java-driver/issues/271

**Comment by rashtao** [comment] 2019-08-07 10:47
related slack thread: https://arangodb-community.slack.com/archives/C1R9YA869/p1561033350006100

**Comment by rashtao** [comment] 2019-08-09 09:49
It could be caused by the usage of the `INTERNAL` (de)Serializer instead of the `CUSTOM` one.
As eg: https://github.com/arangodb/arangodb-java-driver/blob/5e7add2c19150830c8ed0bcc17e647372e780286/src/main/java/com/arangodb/internal/ArangoExecutor.java#L47

**Comment by rocketraman** [comment] 2019-08-09 14:33
> It could be caused by the usage of the `INTERNAL` (de)Serializer instead of the `CUSTOM` one.

Yup. As per my OP:

> ArangoExecutor upon initialization always requests the INTERNAL serializer, even if a custom one is defined.

**Comment by rashtao** [comment] 2019-08-30 13:34
fixed in https://github.com/arangodb/arangodb-java-driver-async/releases/tag/v6.0.0

**Closed as completed** 2019-08-30 13:34 UTC
